### PR TITLE
Handle Optic Issues

### LINKED ISSUE #62: [Optic CI] Type changes are breaking changes
If a property's type changes, this is a breaking change that requires a new version (lifecycle rule, CC @acunniffe)

### LINKED ISSUE #96: Misleading naming rule error message
I think the error message should read "must have snake case keys" here:

```
  FAIL  GET /orgs/{org_id}/apps/{client_id}
  x requirement for field: clientId must have camel case keys
    expected false to be truthy
    at (/path/to/resources/schemas/models/app.yaml:21:432)
  x requirement for field: redirectUris must have camel case keys
    expected false to be truthy
    at (/path/to/resources/schemas/models/app.yaml:26:589)
  x requirement for field: isPublic must have camel case keys
    expected false to be truthy
```

CC @acunniffe

### LINKED ISSUE #102: Tenancy rule failing when it seems like it shouldn't be
After landing #99, I had to update our e2e example specs in #101 to satisfy the org tenancy requirements.

Even with all paths having been prefixed by `/orgs/{org_id}`, a tenancy rule is still failing.

```
$ /Users/cmars/Projects/sweater-comb/node_modules/.bin/ts-node src/index.ts compare --from ./end-end-tests/api-standards/resources/thing/2021-11-10/000-baseline.yaml --to ./end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml
...
  FAIL   This Specification
  x this specification:  must have an org or group tenant
    expected support for org or group tenant: expected [] to have a length above 0 but got 0
    at (/Users/cmars/Projects/sweater-comb/end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml:3:120)
...
```

### LINKED ISSUE #103: Spectral OAS rules failing when they shouldn't be
The Spectral OAS integration seems to be failing on false positives. When I follow these "unused component" errors, they point at locally referenced components that are indeed referenced from the OpenAPI spec.

```
$ /Users/cmars/Projects/sweater-comb/node_modules/.bin/ts-node src/index.ts compare --to ./end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml
...
  FAIL   This Specification
...
  x requirement  must oas3-unused-component
    Potentially unused component has been detected.
    at (/Users/cmars/Projects/sweater-comb/end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml:150:8158)
  x requirement  must oas3-unused-component
    Potentially unused component has been detected.
    at (/Users/cmars/Projects/sweater-comb/end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml:158:8306)
  x requirement  must oas3-unused-component
    Potentially unused component has been detected.
    at (/Users/cmars/Projects/sweater-comb/end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml:167:8500)
  x requirement  must oas3-unused-component
    Potentially unused component has been detected.
    at (/Users/cmars/Projects/sweater-comb/end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml:175:8847)
  x requirement  must oas3-unused-component
    Potentially unused component has been detected.
    at (/Users/cmars/Projects/sweater-comb/end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml:183:9212)
  x requirement  must oas3-unused-component
    Potentially unused component has been detected.
    at (/Users/cmars/Projects/sweater-comb/end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml:196:9672)
  x requirement  must oas3-unused-component
    Potentially unused component has been detected.
    at (/Users/cmars/Projects/sweater-comb/end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml:202:9849)
  x requirement  must oas3-unused-component
    Potentially unused component has been detected.
    at (/Users/cmars/Projects/sweater-comb/end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml:206:9949)
...
```

Running `spectral lint` does not have these errors:

```
$ spectral lint ./end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml
OpenAPI 3.x detected
OpenAPI 3.0.x detected

/Users/cmars/Projects/sweater-comb/end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml
 5:6  warning  info-contact      Info object should contain `contact` object.                             info
 5:6  warning  info-description  OpenAPI object info `description` must be present and non-empty string.  info

✖ 2 problems (0 errors, 2 warnings, 0 infos, 0 hints)
```

### LINKED ISSUE #104: Can't add a new resource version at a higher stability than wip
The stability change rule seems to be catching a false positive on new specs when they are introduced at a level higher than wip. We do want to allow a new resource version to be introduced at any level -- it's just that once it has been, it cannot be changed.

```
$ /Users/cmars/Projects/sweater-comb/node_modules/.bin/ts-node src/index.ts compare --to ./end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml
Loading specifications for comparison:
Current specification: done
Next specification: done


  FAIL   Resource Document
  x published stability:  must not change unless it was wip
    expected undefined to equal 'experimental'
    at (/Users/cmars/Projects/sweater-comb/end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml:4:135)

```

### LINKED ISSUE #106: Changing `format:` or `pattern:` on a string parameter or property should be a breaking change
Changing format or pattern should not be allowed within a resource version as it's a breaking change.

Example (using test cases introduced in #105):

```
$ diff end-end-tests/api-standards/resources/thing/2021-11-10/000-baseline.yaml end-end-tests/api-standards/resources/thing/2021-11-10/001-fail-format-change.yaml
227c227,228
<         format: uuid
---
>         # Should fail: changing from a UUID to a base64 string is breaking
>         format: byte
274c275,277
<           example: thing
---
>           example: bob
>           # Should fail: introducing a more restrictive pattern is a breaking change
>           pattern: "^bob$"
```

### PR DESCRIPTION
**Pull request by smizell**
This address the following issues:

* Resolves #62
  (note, the check in the issue will not fail because the property is added there, not changed)
* Resolves #96 
* Resolves #102
  (note, it was checking for exact match, now it checks with `startsWith` for the path)
* Resolves #103
  (note, turned the rule off) 
* Resolves #104 
* Resolves #106 
  (note: since this checks at the operation request or response level, the error may show up multiple times if its from a ref)

### CODE REVIEW

File: src/service.ts [hunk 1]
```diff
@@ -45,6 +45,7 @@ export function newSnykApiCheckService() {
       "info-description": "off",
       "info-license": "off",
       "license-url": "off",
+      "oas3-unused-component": "off",
```
Comment (acunniffe) [inline src/service.ts:48]: temporary till post prod

File: src/rulesets/api-lifeycle.ts [hunk 2]
```diff
@@ -30,6 +30,9 @@ export const rules = {
       "not change unless it was wip",
       (before, after, context, docs) => {
         if (!before && !after) return;
+        // Allow for creating new resource versions with any stability.
+        // No `before` means this is a new resource
+        if (!before) return;
         if (before === "wip") return;
         expect(before).to.equal(after);
```
Comment (cmars) [inline src/rulesets/api-lifeycle.ts:37]: What about the case where `after` is removed, but it's sunset-eligible to be removed?

File: src/rulesets/properties.ts [hunk 3]
```diff
@@ -23,9 +24,35 @@ function withinAttributes(context) {
...
+  return (parameterBefore, parameterAfter, context) => {
+    let beforeSchema = (parameterBefore.flatSchema ||
+      {}) as OpenAPIV3.SchemaObject;
+    let afterSchema = (parameterAfter.flatSchema ||
+      {}) as OpenAPIV3.SchemaObject;
+    if (!beforeSchema[property] && !afterSchema[property]) return;
+    expect(
+      beforeSchema[property],
+      `expected ${bodyPropertyName(context)} ${property} to not change`,
+    ).to.equal(afterSchema[property]);
```
[the remark this answers is not in the document]
Comment (cmars) [reply src/rulesets/properties.ts:49]: Dropping a constraint, going from more restrictive, to less restrictive, should be OK. So in the case of the `minimum` and `maximum` attributes, if you removed them, that would be non-breaking, because existing clients will still satisfy the looser constraints.

I don't think we need to do exhaustive type analysis on changes in `type`, `format` or `pattern` to detect a compatible looser constraint and allow it; it's fine to keep things simple for these and just not allow them to change within a version.

**Review by cmars — COMMENTED** [review]
Thanks for this! Some concerns below about potential false positives. Would be good to have test coverage demonstrating these.

File: src/rulesets/api-lifeycle.ts (hunk 2 above)
Comment (smizell) [reply src/rulesets/api-lifeycle.ts:37]: I'm currently working on handling sunset rules in another PR and another rule function. Do you think that will cover this scenario?

File: src/rulesets/properties.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (cmars) [reply src/rulesets/properties.ts:49]: Ok... I think I see what's going on here. `property` passed in here, is the schema property that is not allowed to change. Perhaps `schemaProperty` would be a clearer name for this? Or a jsdoc comment on function?

File: src/rulesets/operations.ts [hunk 4]
```diff
@@ -2,9 +2,25 @@ import { SnykApiCheckDsl } from "../dsl";
...
+    parameterBefore: OpenApiRequestParameterFact,
+    parameterAfter: OpenApiRequestParameterFact,
+  ) => {
+    let beforeSchema = (parameterBefore.schema || {}) as OpenAPIV3.SchemaObject;
+    let afterSchema = (parameterAfter.schema || {}) as OpenAPIV3.SchemaObject;
+    if (!beforeSchema[property] && !afterSchema[property]) return;
+    expect(
+      beforeSchema[property],
+      `expected ${parameterAfter.name} parameter ${property} to not change`,
+    ).to.equal(afterSchema[property]);
```
[the remark this answers is not in the document]
Comment (cmars) [reply src/rulesets/operations.ts:20]: Same update here as below; I missed `property` is actually the schema property (like `format`) and not the property itself.

File: src/rulesets/properties.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (smizell) [reply src/rulesets/properties.ts:49]: Agreed. I'll change it up.

File: src/rulesets/api-lifeycle.ts (hunk 2 above)
Comment (cmars) [reply src/rulesets/api-lifeycle.ts:37]: I think it should. So perhaps here, `if (!before || !after) return;` and let the sunset rule catch any premature removal of `after`.

Comment (smizell) [reply src/rulesets/api-lifeycle.ts:37]: Ah, you're right there. I'll change that.

**Comment by smizell** [comment]
@cmars I've tried to address your comments here. I added comments in the code to help explain what's going on. Let me know if you see anything that needs more attention.

File: src/rulesets/api-lifeycle.ts [hunk 5]
```diff
@@ -29,10 +29,10 @@ export const rules = {
     stability.must(
       "not change unless it was wip",
       (before, after, context, docs) => {
-        if (!before && !after) return;
-        // Allow for creating new resource versions with any stability.
-        // No `before` means this is a new resource
-        if (!before) return;
+        // When there is no `before`, it means it's a new file. Any stability is allowed.
+        // When there is no `after`, it means it's been deleted and sunset rules should apply in another rule.
```
Comment (cmars) [inline src/rulesets/api-lifeycle.ts:33]: ❤️

File: src/rulesets/operations.ts [hunk 6]
```diff
@@ -2,9 +2,25 @@ import { SnykApiCheckDsl } from "../dsl";
 import { camelCase, snakeCase } from "change-case";
 import { OpenAPIV3 } from "@useoptic/api-checks";
 import { expect } from "chai";
+import { OpenApiRequestParameterFact } from "@useoptic/openapi-utilities";
 
 const prefixRegex = /^(get|create|list|update|delete)[A-Z]+.*/; // alternatively we could split at camelCase boundaries and assert on the first item
 
+const preventParameterChange = (property: string) => {
```
Comment (cmars) [inline src/rulesets/operations.ts:9]: Please add a similar jsdoc comment here as well.

**Review by cmars — APPROVED** [review]

File: src/rulesets/operations.ts (hunk 6 above)
Comment (smizell) [reply src/rulesets/operations.ts]: Done!

**Review by cmars — APPROVED** [review]
