### PR TITLE
fix: required properties must be declared

### LINKED ISSUE #240: required properties must be declared
Declaring required properties that are not actually properties of the object will never be satisfied, so should not be allowed.

### PR DESCRIPTION
**Pull request by cmars**
This should be considered a backward-compatible requirement because an
object schema which declares required properties that are not declared
will never pass request or response validation.

Fixes #240.

### CODE REVIEW

File: src/rulesets/rest/2022-05-25/property-rules.ts [hunk 1]
```diff
@@ -185,6 +185,54 @@ const arrayWithItemsInResponse = new ResponseBodyRule({
...
+      "declare required properties in objects",
+      (body) => {
+        checkRequiredProperties(body.raw.schema as OpenAPIV3.SchemaObject);
+      },
+    );
+  },
+});
+
+const checkRequiredProperties = (schema: OpenAPIV3.SchemaObject) => {
+  const schemas = [schema];
```
Comment (jcsackett) [inline src/rulesets/rest/2022-05-25/property-rules.ts:213]: Since we're only ever passing one schema, and you then operate on schemas independently in the while loop, why make this an array? Seems like it would be simpler to just operate on the passed in schema then wrap it like this.

I'm assuming there's a detail to this that I'm missing which requires an array?

**Review by jcsackett — APPROVED** [review]
LGTM, but I'm confused by a detail in the actual checker.

File: src/rulesets/rest/2022-05-25/property-rules.ts (hunk 1 above)
Comment (cmars) [reply src/rulesets/rest/2022-05-25/property-rules.ts:213]: Conceptually this is doing a recursive check on all properties which are themselves objects, but an array is being used as a stack here to eliminate that recursion since TS isn't tail-call optimized.
